name: ${project.name}
version: ${project.version}
author: gzx
main: net.twilightdevelopment.plugin.autohub.AutoHub
api-version: 1.13

commands:
  sethub:
    description: Sets the hub location
    usage: /sethub <x> <y> <z> [world]
    
  hub:
    description: Teleports player to the hub location, or, if set, the server set in the config
    usage: /hub

  autohub:
    description: Base command for AutoHub utility tasks
    usage: /autohub (reload | info)
    
permissions:
  autohub.set:
    description: Allows you to set the hub
    default: false
    
  autohub.tphub:
    description: Allows you to use /hub
    default: true
    
  autohub.bypass:
    description: Players with this permission will not be sent to the hub location when they join.
    default: false

  autohub.reload:
    description: Allows you to use /autohub reload
    default: false

  autohub.info:
    description: Allows you to use /autohub info
    default: true