#The location of the hub.
hub:
  
#Setting the following to true will teleport the user to the hub server (BungeeCord required) instead of a location in the current server.
#Note that if this is set to true the tponjoin option will not work.
bungeecord: false 

#If BungeeCord is set to true, fill in te name of the hub server here
bungeeserver:

#Set this to true if you want /hub to work, false if you want it disabled
hubcommand: true

#The message to be sent to the player after doing /hub
#Only will be sent if they are telported to a location on the same server; if they are moved to another server using BungeeCord this will not do anything
hubmessage: You have been teleported to the lobby!

#Make the player teleport to the hub location on join?
tponjoin: true

#The message to be sent to the player after joining
joinmessage: Welcome!

#Enable the update checker?
update-checker: true




