name: AutoHub
version: 1.0
author: gzx
main: net.twilightdevelopment.plugin.autohub.Main

commands:
  sethub:
    description: Sets the hub location
    
  hub:
    description: Teleports player to the hub location, or, if set, the server set in the config
    
permissions:
  autohub.set:
    description: Allows you to set the hub
    default: false
    
  autohub.tphub:
    description: Allows you to use /hub
    default: true
    
  autohub.bypass:
    description: Players with this permission will not be sent to the hub location when they join.
    default: false